version: '3.8'

services:
  naabu-api:
    build: .
    container_name: naabu-api
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - naabu-net

networks:
  naabu-net:
    driver: bridge